import { Leaf, Zap, Flame } from "lucide-react"

export const allQuestions = [
  // EASY
  {
    id: 1,
    question: "What type of waste is a plastic water bottle?",
    options: ["Organic", "Recyclable", "Residual", "Hazardous"],
    correctAnswer: "Recyclable",
    type: "text",
    difficulty: "easy",
    bonus: 0,
  },
  {
    id: 2,
    question: "Which of the following is considered organic waste?",
    options: ["Banana peel", "Glass bottle", "Aluminum can", "Plastic bag"],
    correctAnswer: "Banana peel",
    type: "text",
    difficulty: "easy",
    bonus: 1,
  },
  {
    id: 3,
    question: "What kind of waste is this?",
    imageUrl: "/images/plastic-bottle.jpg",
    options: ["Recyclable", "Hazardous", "Organic", "Residual"],
    correctAnswer: "Recyclable",
    type: "image",
    difficulty: "easy",
    bonus: 2,
  },
  {
    id: 4,
    question: "Used batteries should be disposed of as:",
    options: ["Organic", "Residual", "Recyclable", "Hazardous"],
    correctAnswer: "Hazardous",
    type: "text",
    difficulty: "easy",
    bonus: 3,
  },
  {
    id: 5,
    question: "What type of waste is food scraps?",
    options: ["Recyclable", "Hazardous", "Residual", "Organic"],
    correctAnswer: "Organic",
    type: "text",
    difficulty: "easy",
    bonus: 0,
  },
  {
    id: 6,
    question: "Which item belongs in the recyclable bin?",
    options: ["Old newspaper", "Used tissue", "Crumpled chip bag", "Dirty pizza box"],
    correctAnswer: "Old newspaper",
    type: "text",
    difficulty: "easy",
    bonus: 0,
  },
  {
    id: 7,
    question: "What kind of waste is this?",
    imageUrl: "/images/aluminum-can.jpg",
    options: ["Organic", "Residual", "Recyclable", "Hazardous"],
    correctAnswer: "Recyclable",
    type: "image",
    difficulty: "easy",
    bonus: 1,
  },
  {
    id: 8,
    question: "Broken ceramics are classified as:",
    options: ["Recyclable", "Organic", "Residual", "Hazardous"],
    correctAnswer: "Residual",
    type: "text",
    difficulty: "easy",
    bonus: 0,
  },
  {
    id: 9,
    question: "What type of waste is expired medicine?",
    options: ["Organic", "Hazardous", "Recyclable", "Residual"],
    correctAnswer: "Hazardous",
    type: "text",
    difficulty: "easy",
    bonus: 2,
  },
  {
    id: 10,
    question: "What kind of waste is this?",
    imageUrl: "/images/fruit-peel.jpg",
    options: ["Hazardous", "Residual", "Recyclable", "Organic"],
    correctAnswer: "Organic",
    type: "image",
    difficulty: "easy",
    bonus: 1,
  },
  // MEDIUM
  {
    id: 11,
    question: "Which bin should you use for eggshells?",
    options: ["Recyclable", "Hazardous", "Organic", "Residual"],
    correctAnswer: "Organic",
    type: "text",
    difficulty: "medium",
    bonus: 0,
  },
  {
    id: 12,
    question: "Used cooking oil is considered:",
    options: ["Organic", "Hazardous", "Recyclable", "Residual"],
    correctAnswer: "Hazardous",
    type: "text",
    difficulty: "medium",
    bonus: 3,
  },
  {
    id: 13,
    question: "What kind of waste is this?",
    imageUrl: "/images/newspaper.jpg",
    options: ["Residual", "Recyclable", "Hazardous", "Organic"],
    correctAnswer: "Recyclable",
    type: "image",
    difficulty: "medium",
    bonus: 2,
  },
  {
    id: 14,
    question: "Pizza boxes with grease belong to:",
    options: ["Recyclable", "Organic", "Residual", "Hazardous"],
    correctAnswer: "Residual",
    type: "text",
    difficulty: "medium",
    bonus: 4,
  },
  {
    id: 15,
    question: "Tea bags (with staples) are:",
    options: ["Organic", "Recyclable", "Residual", "Hazardous"],
    correctAnswer: "Residual",
    type: "text",
    difficulty: "medium",
    bonus: 3,
  },
  {
    id: 16,
    question: "What kind of waste is this?",
    imageUrl: "/images/broken-glass.jpg",
    options: ["Recyclable", "Hazardous", "Residual", "Organic"],
    correctAnswer: "Residual",
    type: "image",
    difficulty: "medium",
    bonus: 0,
  },
  {
    id: 17,
    question: "Which of these is NOT recyclable?",
    options: ["Plastic bottle", "Glass jar", "Styrofoam cup", "Aluminum can"],
    correctAnswer: "Styrofoam cup",
    type: "text",
    difficulty: "medium",
    bonus: 5,
  },
  {
    id: 18,
    question: "What type of waste is hair from brushing?",
    options: ["Organic", "Residual", "Recyclable", "Hazardous"],
    correctAnswer: "Organic",
    type: "text",
    difficulty: "medium",
    bonus: 1,
  },
  {
    id: 19,
    question: "What kind of waste is this?",
    imageUrl: "/images/candy-wrapper.jpg",
    options: ["Recyclable", "Organic", "Residual", "Hazardous"],
    correctAnswer: "Residual",
    type: "image",
    difficulty: "medium",
    bonus: 2,
  },
  {
    id: 20,
    question: "Which bin for coffee grounds?",
    options: ["Organic", "Recyclable", "Hazardous", "Residual"],
    correctAnswer: "Organic",
    type: "text",
    difficulty: "medium",
    bonus: 0,
  },
  // HARD
  {
    id: 21,
    question: "Old mobile phones are:",
    options: ["Residual", "Hazardous", "Recyclable", "Organic"],
    correctAnswer: "Recyclable",
    type: "text",
    difficulty: "hard",
    bonus: 6,
  },
  {
    id: 22,
    question: "What kind of waste is this?",
    imageUrl: "/images/battery.jpg",
    options: ["Organic", "Recyclable", "Hazardous", "Residual"],
    correctAnswer: "Hazardous",
    type: "image",
    difficulty: "hard",
    bonus: 8,
  },
  {
    id: 23,
    question: "Soiled paper napkins go to:",
    options: ["Recyclable", "Organic", "Residual", "Hazardous"],
    correctAnswer: "Residual",
    type: "text",
    difficulty: "hard",
    bonus: 0,
  },
  {
    id: 24,
    question: "Dry leaves are classified as:",
    options: ["Residual", "Hazardous", "Organic", "Recyclable"],
    correctAnswer: "Organic",
    type: "text",
    difficulty: "hard",
    bonus: 2,
  },
  {
    id: 25,
    question: "What kind of waste is this?",
    imageUrl: "/images/lightbulb.jpg",
    options: ["Residual", "Hazardous", "Recyclable", "Organic"],
    correctAnswer: "Hazardous",
    type: "image",
    difficulty: "hard",
    bonus: 7,
  },
  {
    id: 26,
    question: "Plastic straws are:",
    options: ["Recyclable", "Residual", "Organic", "Hazardous"],
    correctAnswer: "Residual",
    type: "text",
    difficulty: "hard",
    bonus: 0,
  },
  {
    id: 27,
    question: "Which item is hazardous waste?",
    options: ["Banana peel", "Paint can", "Cardboard box", "Glass bottle"],
    correctAnswer: "Paint can",
    type: "text",
    difficulty: "hard",
    bonus: 5,
  },
  {
    id: 28,
    question: "What kind of waste is this?",
    imageUrl: "/images/coffee-cup.jpg",
    options: ["Recyclable", "Organic", "Residual", "Hazardous"],
    correctAnswer: "Residual",
    type: "image",
    difficulty: "hard",
    bonus: 3,
  },
  {
    id: 29,
    question: "Used diapers are:",
    options: ["Organic", "Hazardous", "Residual", "Recyclable"],
    correctAnswer: "Residual",
    type: "text",
    difficulty: "hard",
    bonus: 0,
  },
  {
    id: 30,
    question: "Which bin for expired food?",
    options: ["Hazardous", "Residual", "Recyclable", "Organic"],
    correctAnswer: "Organic",
    type: "text",
    difficulty: "hard",
    bonus: 4,
  },
]

export const initialLeaderboard = [
  { name: "Adyfas", score: 95, avatar: "/images/adyfas-ver.jpeg" },
  { name: "Dudi", score: 92, avatar: "/images/person-1.jpg" },
  { name: "Nurhaniifah", score: 88, avatar: "/images/person-2.jpg" },
  { name: "Damara", score: 85, avatar: "/images/person-1.jpg" },
  { name: "Rivano", score: 82, avatar: "/images/person-1.jpg" },
  { name: "Samsudin", score: 80, avatar: "/images/person-1.jpg" },
  { name: "Roy", score: 78, avatar: "/images/person-1.jpg" },
  { name: "Hana", score: 75, avatar: "/images/person-2.jpg" },
]

export const difficultyModes = [
  {
    key: "easy",
    icon: Leaf,
    title: "Easy Mode",
    desc: "5 pts per correct",
    bg: "bg-green-50",
  },
  {
    key: "medium",
    icon: Zap,
    title: "Medium Mode",
    desc: "10 pts per correct",
    bg: "bg-blue-50",
  },
  {
    key: "hard",
    icon: Flame,
    title: "Hard Mode",
    desc: "20 pts per correct",
    bg: "bg-orange-50",
  },
]
